language: rust
cache: cargo

rust:
  - nightly

env:
  matrix:
    - SCRIPT="./check.sh"
    - SCRIPT="./build.sh"
    - SCRIPT="./test.sh"

before_script:
  - rustup target add wasm32-unknown-unknown
  - which wasm-gc || cargo install --git https://github.com/alexcrichton/wasm-gc
  - which cargo-readme || cargo install cargo-readme

script:
  - "$SCRIPT"
