[package]
authors = ["Nick Fitzgerald <fitzgen@gmail.com>"]
name = "intrusive_splay_tree"
version = "0.1.0"

[dependencies]
unreachable = "1.0.0"

[dev-dependencies]
typed-arena = "1.3.0"
quickcheck = "0.6.0"
